import type { Metadata } from "next";
import { Nunito, Orbitron } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-nunito",
});

const orbitron = Orbitron({
  subsets: ["latin"],
  weight: ["700"], // you can adjust the weight as needed
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Cloutcahin",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} ${orbitron.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
